// <auto-generated />
using SEA.DET.TarPit.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SEA.DET.TarPit.Infrastructure.Migrations
{
    [DbContext(typeof(RateLimiterContext))]
    partial class RateLimiterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Postgres.Models.CallRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CalledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CallerId")
                        .HasColumnType("integer")
                        .HasColumnName("caller_id");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nonce");

                    b.HasKey("Id")
                        .HasName("pk_call_records");

                    b.HasIndex("CallerId", "CalledAt")
                        .HasDatabaseName("ix_call_records_caller_id_called_at");

                    b.HasIndex("CallerId", "Nonce")
                        .HasDatabaseName("ix_call_records_caller_id_nonce");

                    b.ToTable("call_records", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Postgres.Models.Caller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<string>("ExternalIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_identifier");

                    b.HasKey("Id")
                        .HasName("pk_callers");

                    b.HasIndex("ExternalIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_callers_external_identifier");

                    b.ToTable("callers", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Postgres.Models.CallRecord", b =>
                {
                    b.HasOne("Infrastructure.Postgres.Models.Caller", "Caller")
                        .WithMany()
                        .HasForeignKey("CallerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_call_records_callers_caller_id");

                    b.Navigation("Caller");
                });
#pragma warning restore 612, 618
        }
    }
}
